export const DEMO_APPLICATION_FORM_CONFIG = {
  metadata: {
    id: "demo-application",
    name: "Demo Application Form - Enhanced with Zod Validation",
    formType: "APPLICATION_FORM",
  },
  steps: [
    {
      id: "personal-info",
      name: "Personal Information",
      description: "Please provide your basic personal information",
      order: 1,
      fields: [
        {
          id: "firstName",
          name: "firstName",
          type: "text",
          label: "First Name",
          required: true,
          placeholder: "Enter your first name",
          helpText: "Your legal first name as it appears on official documents",
          validation: ["required", { minLength: 2 }, { maxLength: 50 }],
          grid: { xs: 12, sm: 6 },
        },
        {
          id: "lastName",
          name: "lastName",
          type: "text",
          label: "Last Name",
          required: true,
          placeholder: "Enter your last name",
          helpText: "Your legal last name as it appears on official documents",
          validation: [
            "required",
            { minLength: 2 },
            { maxLength: 50 },
            { pattern: "^[a-zA-Z\\s\\-']+$" },
          ],
          grid: { xs: 12, sm: 6 },
        },
        {
          id: "email",
          name: "email",
          type: "email",
          label: "Email Address",
          required: true,
          placeholder: "Enter your email address",
          helpText: "We will use this email for important communications",
          validation: ["required", "email", { maxLength: 100 }],
          grid: { xs: 12 },
        },
        {
          id: "phone",
          name: "phone",
          type: "phone",
          label: "Phone Number",
          required: true,
          placeholder: "(555) 123-4567",
          helpText: "US phone number for verification",
          validation: ["required", "phoneUS"],
          grid: { xs: 12, sm: 6 },
        },
        {
          id: "dateOfBirth",
          name: "dateOfBirth",
          type: "date",
          label: "Date of Birth",
          required: true,
          helpText: "Must be 18 years or older",
          validation: ["required", "date"],
          grid: { xs: 12, sm: 6 },
        },
      ],
    },
    {
      id: "application-details",
      name: "Application Details",
      description:
        "Tell us about your application preferences and financial information",
      order: 2,
      fields: [
        {
          id: "applicationType",
          name: "applicationType",
          type: "radio",
          label: "Application Type",
          required: true,
          helpText:
            "Choose individual for sole applicant or joint for multiple applicants",
          options: [
            {
              value: "individual",
              label: "Individual Application",
              description: "You are the sole applicant",
            },
            {
              value: "joint",
              label: "Joint Application",
              description: "Multiple applicants (spouse, partner, etc.)",
            },
          ],
          validation: ["required", { oneOf: ["individual", "joint"] }],
          grid: { xs: 12 },
        },
        {
          id: "loanAmount",
          name: "loanAmount",
          type: "currency",
          label: "Desired Loan Amount",
          required: true,
          placeholder: "$250,000",
          helpText: "Enter the total amount you wish to borrow",
          validation: [
            "required",
            "currency",
            { min: 50000 },
            { max: 2000000 },
          ],
          grid: { xs: 12, sm: 6 },
        },
        {
          id: "propertyValue",
          name: "propertyValue",
          type: "currency",
          label: "Estimated Property Value",
          required: true,
          placeholder: "$350,000",
          helpText: "Current market value of the property",
          validation: [
            "required",
            "currency",
            { min: 75000 },
            { max: 5000000 },
          ],
          grid: { xs: 12, sm: 6 },
        },
        {
          id: "downPayment",
          name: "downPayment",
          type: "currency",
          label: "Down Payment",
          required: true,
          placeholder: "$50,000",
          helpText: "Amount you plan to put down",
          validation: ["required", "currency", { min: 0 }],
          dependencies: ["loanAmount", "propertyValue"],
          grid: { xs: 12, sm: 6 },
        },
        {
          id: "annualIncome",
          name: "annualIncome",
          type: "currency",
          label: "Annual Income",
          required: true,
          placeholder: "$75,000",
          helpText: "Your total annual gross income",
          validation: [
            "required",
            "currency",
            { min: 20000 },
            { max: 10000000 },
          ],
          grid: { xs: 12, sm: 6 },
        },
        {
          id: "propertyZipCode",
          name: "propertyZipCode",
          type: "text",
          label: "Property ZIP Code",
          required: true,
          placeholder: "12345",
          helpText: "ZIP code of the property location",
          validation: ["required", "zipCodeUS"],
          grid: { xs: 12, sm: 6 },
        },
      ],
    },
    {
      id: "confirmation",
      name: "Review & Confirmation",
      description:
        "Please review your information and provide final confirmations",
      order: 3,
      fields: [
        {
          id: "agreeToTerms",
          name: "agreeToTerms",
          type: "checkbox",
          label: "I agree to the Terms and Conditions",
          required: true,
          helpText: "You must agree to proceed with the application",
          validation: ["required"],
          grid: { xs: 12 },
        },
        {
          id: "agreeToPrivacy",
          name: "agreeToPrivacy",
          type: "checkbox",
          label: "I agree to the Privacy Policy",
          required: true,
          helpText: "Required for processing your personal information",
          validation: ["required"],
          grid: { xs: 12 },
        },
        {
          id: "marketingConsent",
          name: "marketingConsent",
          type: "checkbox",
          label: "I would like to receive marketing communications",
          required: false,
          helpText: "Optional: Receive updates about products and services",
          grid: { xs: 12 },
        },
        {
          id: "additionalComments",
          name: "additionalComments",
          type: "textarea",
          label: "Additional Comments (Optional)",
          required: false,
          placeholder: "Any additional information you would like to share...",
          helpText:
            "Optional: Provide any additional context for your application",
          validation: [{ maxLength: 500 }],
          grid: { xs: 12 },
        },
        {
          id: "referralSource",
          name: "referralSource",
          type: "dropdown",
          label: "How did you hear about us?",
          required: false,
          placeholder: "Select an option...",
          helpText: "Optional: Help us understand how customers find us",
          options: [
            { value: "search", label: "Internet Search" },
            { value: "social", label: "Social Media" },
            { value: "referral", label: "Friend/Family Referral" },
            { value: "advertisement", label: "Advertisement" },
            { value: "realtor", label: "Real Estate Agent" },
            { value: "other", label: "Other" },
          ],
          validation: [
            {
              oneOf: [
                "search",
                "social",
                "referral",
                "advertisement",
                "realtor",
                "other",
              ],
            },
          ],
          grid: { xs: 12, sm: 6 },
        },
      ],
    },
  ],
};
